### ISSUE TITLE
Health Style Won't Change to Cross and Some Colours Don't Change as well

### ISSUE THREAD

**Issue by Reservater** [CriticalFlaw/TF2HUD.Editor#43] opened 2021-04-18 04:06 UTC
On Flawhud, when I change health buffed to a different colour it won't change for the medigun so it will remain the default dark green for buffed health and dark red for low health instead of the colours I want to use, also for what ever reason the health style cross doesn't work and instead uses a combination of both the default(for the ammo counter) and coloured text health style instead of the cross which also applies to the medigun's health icons as well.

**Comment by CriticalFlaw** [comment] 2021-04-18 14:45
There's a separate color option for the UberCharge, buffed health only changes the color of your health when buffed. Also changes to colors require the game to be restarted for it to take effect.

The cross is working as intended. There's no cross for ammo and the combination of color health and the cross was done so that you could still see the health amount in front of the cross. Otherwise you wouldn't be able to see it because they're both white.

**Comment by Reservater** [comment] 2021-04-18 15:39
![image](https://user-images.githubusercontent.com/53986576/115150514-1742b980-a0ac-11eb-9d55-8e507a3ab4e1.png)
These are my settings from today and I did restart tf2 but cross style didn't take effect and instead was colored text even though I selected cross.

I have a few screenshots from an earlier version of Flawhud from a few months ago and it should look something like this when cross is selected.
![image](https://user-images.githubusercontent.com/53986576/115150658-b5cf1a80-a0ac-11eb-9836-12c28d1de356.png)
![image](https://user-images.githubusercontent.com/53986576/115150660-bcf62880-a0ac-11eb-903d-1e08e4a3f7e1.png)

But When Cross is selected in the latest version of flawhud/hud editor its basically just colored text and I took these screenshots recently and I didn't change the health style to colored text and I kept it on Cross after restarting tf2 and I made sure to apply the changes in the editor multiple times.
![image](https://user-images.githubusercontent.com/53986576/115150713-f0d14e00-a0ac-11eb-9de0-452561906aed.png)
![image](https://user-images.githubusercontent.com/53986576/115150793-4f96c780-a0ad-11eb-9c06-4307ef22ed6e.png)

Also, I was referring to how cross would make the ammo counter use both color and default background not the combination of colour and health.
![image](https://user-images.githubusercontent.com/53986576/115151321-b9b06c00-a0af-11eb-8d0a-12039a341fe5.png)

The colours for buffed and low health does change but it doesn't apply to the medigun except for ubercharging.
![image](https://user-images.githubusercontent.com/53986576/115151378-f2504580-a0af-11eb-9e4a-3a79ddf0f1a5.png)

**Comment by CriticalFlaw** [comment] 2021-04-18 18:47
You're right, I see where the problem is now. The property for the health cross was not referencing an image for the cross so it had nothing to display when the option was enabled. I added it back now, so you'll just have to reinstall flawhud

7a740e2fbfb2c5a9921a7a85299e584efaa7293d

**Comment by CriticalFlaw** [comment] 2021-04-18 18:51
The health and ammo values changing colors will need to changed in the editor so that they stay white when the cross is enabled, that way the ammo will still have the red background when low, but won't color the ammo values which would make them hard to see.

**Comment by CriticalFlaw** [comment] 2021-04-18 18:53
> The colours for buffed and low health does change but it doesn't apply to the medigun except for ubercharging.

Still not sure what you mean here. Are you referring to the health value in the TargetID still using the dark green instead of lime color?

**Comment by Reservater** [comment] 2021-04-19 02:49
> 
> Still not sure what you mean. Are you referring to the health value in the TargetID still using the dark green instead of lime color?

Yes

**Comment by CriticalFlaw** [comment] 2021-04-19 03:02
Those are controlled by a different color value, not the same one as for your health. It could be added to be changed by the editor though.

**Comment by Reservater** [comment] 2021-04-19 03:04
Ok thanks for the help

**Comment by CriticalFlaw** [comment] 2021-04-19 03:58
I've updated the flawhud schema file to not color the health and ammo values when the health cross is enabled and also made it update the color value for the health seen on the TargetID. This change will be released in version 2.1 - thank you for reporting it! 7b6c8101cfe0bb5235e6ca24d8788198515dab80

**Closed** 2021-04-19 04:26 UTC
Labels: bug, flawhud
