### ISSUE TITLE
[flawhud] Updated for recent changes.

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#203] opened 2023-07-23 11:15 UTC
How its intended to look:
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/2c0ee6d1-4cf3-4336-9b45-92435d7ca5a9)

How my game looks:
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/5fb26e08-599e-4735-a5a4-7e70bdd12b11)

The recent changes seem to be broken for me after a fresh install through the editor (github has same issues) The disguise panel location hasnt changed and the missed currency is in the wrong spot and has a weird white box behind it

![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/277ed01d-284d-48cc-b1ec-4577b6d050cc)

Centered MVM currency also suffers an issue with the shadow behind remaining currency number being misplaced

**Comment by Presto06** [comment] 2023-07-23 14:08
> This should be opened in the HUD editor GitHub as the schema needs to be updated, not the HUD itself.
> 
> I'm also going to change the editor to download from the release page by default instead of the master branch. Developmental changes will always not match the schema and will likely only be updated once a full release is made.

I was originally going to do that but when I downloaded flawhud from its github page (no editor) the issues were still present

**Comment by Presto06** [comment] 2023-07-23 14:12
Sorry im dumb, I forgot to uninstall the hud editor version

You are right its an issue with the hud editor

Sorry for any inconvenience

**Comment by CriticalFlaw** [comment] 2023-07-23 14:14
No worries, it happens. I've updated the Editor schema to have two separate branches; stable and dev.

- `stable` - will pull from the latest release version (for now it will pull from before these recent changes so all customizations will still work as intended.
- `dev` - pulls the latest from the master branch which will have latest but potentially breaking changes.
![image](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/6818236/5b49268a-6262-49fc-a2a3-5253caec337c)

**Comment by Presto06** [comment] 2023-07-23 14:24
> No worries, it happens. I've updated the Editor schema to have two separate branches; stable and dev.
> 
> * `stable` - will pull from the latest release version (for now it will pull from before these recent changes so all customizations will still work as intended).
> * `dev` - pulls the latest from the master branch which will have latest but potentially breaking changes.
> 
> ![image](https://user-images.githubusercontent.com/6818236/255398544-5b49268a-6262-49fc-a2a3-5253caec337c.png)

Yep thats probably for the best since it can be annoying downloading experimental versions with bugs and it saves people from making bug reports and gives you time working on the hud, win win :D

**Comment by CriticalFlaw** [comment] 2023-07-23 15:02
Agreed. I'll update the schema before making the official release (probably in the next month or so). Closing this for now. Cheers.

**Closed by CriticalFlaw** 2023-07-23 15:02 UTC
Labels: hud-bug
