### ISSUE TITLE
[zeeshud] Cikandei font doesn't work.

### ISSUE THREAD

**Issue by rigtbh** [CriticalFlaw/TF2HUD.Editor#175] opened 2023-03-03 15:05 UTC
Im sure this isn't about the hud editor but it exists
![resim](https://user-images.githubusercontent.com/87094688/222754280-7d42038b-d678-40a1-8e3b-f6d65a9e455e.png)
![resim](https://user-images.githubusercontent.com/87094688/222754480-c7dcaf1b-c462-4e72-87fd-5f6b575c4546.png)

**Comment by CriticalFlaw** [comment] 2023-03-22 02:37
Unfortunately, there's no way to fix this with the editor - it would need to be fixed in zeeshud. The issue is in the file `zeeshud/resource/ui/hudplayerhealth.res` where the #base statements are in such an order that the health font in your screenshot will always take precedence.

The fix would be changing the file contents to something like this, putting the line with `health-ammo_alt_font` at the bottom of that group to allow for health changes made in futura, classic and ut to take effect.

```
#base "..\..\#customizations\addons\_enabled\disable_images\player_health.res"

#base "..\..\#customizations\addons\_enabled\health-ammo_font_futura\player_health.res"
#base "..\..\#customizations\addons\_enabled\health-ammo-style_classic\player_health.res"
#base "..\..\#customizations\addons\_enabled\health-ammo-style_ut\player_health.res"
#base "../../#customizations/addons/_enabled/health-ammo_alt_font/player_health.res"

#base "..\..\#customizations\addons\_enabled\status_indicators\health_status_indicator.res"

#base "..\..\_zeeshud_base\ingame_bottom_left\player_health.res"
```

Worth a try opening an issue ticket on the zeeshud repo in hopes this gets implemented. Thanks for reporting the issue.

**Closed by CriticalFlaw** 2023-03-22 02:37 UTC
Labels: hud-bug
