### ISSUE TITLE
Main Menu is almost completely white

### ISSUE THREAD

**Issue by Golden-Gold** [CriticalFlaw/TF2HUD.Editor#99] opened 2021-09-25 01:38 UTC
**Describe the issue**
Main Menu has no text, and is almost completely white, seemingly working when loading.

**Steps to reproduce**
Steps to reproduce the issue:
Unknown, as this issue happens no matter what i do.

**Screenshots**
There are two screenshots below that show the editor settings, and the result, (result does not change no matter what settings or hud is used.)

**Desktop (please complete the following information):**
 Windows 10
 2.3.1
 Sunset HUD

![TF2 HUD Editor 9_24_2021 8_29_46 PM](https://user-images.githubusercontent.com/91354786/134753450-0cdf81b9-01c5-433e-b209-89d282765a0c.png)

![Team Fortress 2 9_24_2021 8_26_52 PM](https://user-images.githubusercontent.com/91354786/134753458-70d5e037-0346-431a-a64f-35fc8b763c09.png)

**Comment by CriticalFlaw** [comment] 2021-09-28 16:02
This is a duplicate of https://github.com/CriticalFlaw/TF2HUD.Editor/issues/92. The download package for sunsetHud is structured differently from other huds and is incompatible with the editor. It was decided to pull SunsetHud from the supported list until that could be resolved.

**Closed by CriticalFlaw** 2021-09-28 16:02 UTC
Labels: bug
